AXIS-2850: Removed the inherently non thread-safe Service#getCall() method and solved a thread safety issue involving Service#createCall(). The removed method is part of the public API, but: * It is deprecated since Axis 1.2. * People generally prefer build failures or NoSuchMethodErrors over dealing with subtle concurrency issues that only show up in production systems and that are not reproducible.